### ISSUE TITLE
Propose Animation

### ISSUE THREAD

**Issue by naufaldi** [logos-engineer/logos-fest#39]
1. Framer Motion (https://github.com/framer/motion ) 
   - Pendekatan perkomponen [ItsFaqih](https://github.com/itsfaqih/fama)
   - Pendekatan dengan perpage transisi [Theodrus Web](https://github.com/theodorusclarence/theodorusclarence.com)

2. AOS (https://michalsnik.github.io/aos/)
3. Anime.js (https://animejs.com/)
4. Lainnya

**Comment by Aqshola** [comment]
make framer?, nanti buat landing dibikin perkomponen, terus page lain dipakein transisi? cc mas @naufaldi

**Comment by naufaldi** [comment]
oke deh pkek framer , aku setup framernya

**Comment by Aqshola** [comment]
Issue at #62  PR  at #64
